// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtFXA3VfcTanVQ2wQK4BXHzwNpacRHKuw',
    appId: '1:911947052300:web:efa2c657e09219ad9e4529',
    messagingSenderId: '911947052300',
    projectId: 'studentinfo-855d9',
    authDomain: 'studentinfo-855d9.firebaseapp.com',
    databaseURL: 'https://studentinfo-855d9-default-rtdb.firebaseio.com',
    storageBucket: 'studentinfo-855d9.appspot.com',
    measurementId: 'G-PMCSNBK52K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnH1SDNB_VH3PYX9aqGpWAiWj9EBpzpno',
    appId: '1:911947052300:android:4de1e4482bc8ef349e4529',
    messagingSenderId: '911947052300',
    projectId: 'studentinfo-855d9',
    databaseURL: 'https://studentinfo-855d9-default-rtdb.firebaseio.com',
    storageBucket: 'studentinfo-855d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGxF2d9FBsKrme3mItz9BR2eDNp9p3SY',
    appId: '1:911947052300:ios:b58ebbc113fe52f39e4529',
    messagingSenderId: '911947052300',
    projectId: 'studentinfo-855d9',
    databaseURL: 'https://studentinfo-855d9-default-rtdb.firebaseio.com',
    storageBucket: 'studentinfo-855d9.appspot.com',
    iosBundleId: 'com.example.studentd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGxF2d9FBsKrme3mItz9BR2eDNp9p3SY',
    appId: '1:911947052300:ios:b58ebbc113fe52f39e4529',
    messagingSenderId: '911947052300',
    projectId: 'studentinfo-855d9',
    databaseURL: 'https://studentinfo-855d9-default-rtdb.firebaseio.com',
    storageBucket: 'studentinfo-855d9.appspot.com',
    iosBundleId: 'com.example.studentd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtFXA3VfcTanVQ2wQK4BXHzwNpacRHKuw',
    appId: '1:911947052300:web:e89ff02b37b29a759e4529',
    messagingSenderId: '911947052300',
    projectId: 'studentinfo-855d9',
    authDomain: 'studentinfo-855d9.firebaseapp.com',
    databaseURL: 'https://studentinfo-855d9-default-rtdb.firebaseio.com',
    storageBucket: 'studentinfo-855d9.appspot.com',
    measurementId: 'G-7SLJB507Q6',
  );
}
